theme: jekyll-theme-minimal
title: Manuel Lleonart Anguix
description: International Doctorate of Economic Analysis
logo: https://github.com/MaLleAn/Tryout/blob/gh-pages/foto_tonto.jpg?raw=true
show_download: true
