theme: jekyll-theme-minimal
title: Manuel Lleonart Anguix
description: International Doctorate of Economic Analysis
logo: https://d500.epimg.net/cincodias/imagenes/2018/11/13/lifestyle/1542113135_776401_1542116070_noticia_normal.jpg
